const occupationCategoryEnum = `
    enum OccupationCategory {
        estudiante
        negociosYAdministracion
        mineriaYExtraccion
        laboresDomesticas
        ingenieriaManufacturaYConstruccion
        arquitecturaYConstruccion
        bellasArtes
        estadistica
        empleadInformal
        cuidadoDeEnfermos
        matematicasYEstadistica
        areaBiologicosYODeLaSalud
        poderJudicial
        cienciasSocialesAdministracionYDerecho
        historiaYArqueologia
        cienciasDeLaTierraYLaAtmosfera
        cienciasSocialesYEstudiosDelComportamiento
        gobiernoLocal
        posgrado
        terapiaYRehabilitacion
        arquitecturaYUrbanismo
        secundaria
        serviciosDeTransporte
        cuidadoDeAdultosMayores
        sociologiaYAntropologia
        servicios
        produccionYExplotacionAgricolaYGanad
        trabajoYAtencionSocial
        mercadotecniaYPublicidad
        tecnicasAudiovisualesYProduccionDeMedios
        negociosYComercio
        humanidades
        saludPublica
        formacionDocenteParaOtrosServiciosEducativos
        veterinaria
        areaDeLasHumanidadesYLasArtes
        empleadEnElSectorPublico
        trabajoDomestico
        tecnologiasDeLaInformacionYComunicacion
        formacionDocenteParaEducacionBasicaNivelSecundaria
        cienciasNaturalesExactasYDeLaComputacion
        gobiernoFederal
        freelancer
        medicina
        cienciasPoliticas
        ingenieriaDeVehiculosDeMotorBarcosYAeronaves
        preparatoria
        negocioPropioYOFamiliar
        ingenieriaQuimica
        ingenieriaIndustrialMecanicaElectronicaYTecnologia
        fisica
        deportes
        cienciasDeLaInformacion
        cienciasAmbientales
        formacionDocenteParaEducacionBasicaNivelPreescolar
        agronomiaYVeterinaria
        areaDelSectorComercial
        comunicacionYPeriodismo
        cienciasNaturales
        universidad
        ingenieriaMecanicaYMetalurgia
        organizacionesDeLaSociedadCivil
        formacionDocenteParaEducacionFisicaArtisticaOTecnologica
        lenguasExtranjeras
        trabajoDomesticoYOFamiliar
        construccionEIngenieriaCivil
        educacion
        areaDeLasCienciasSociales
        orientacionYAsesoriaEducativa
        musicaYArtesEscenicas
        manufacturasYProcesos
        administracionYGestionDeEmpresas
        artes
        cienciasDeLaComputacion
        electronicaYAutomatizacion
        estomatologiaYOdontologia
        derecho
        matematicas
        comerciante
        cuidadoDeFamiliares
        aplicacionesDigitales
        cienciasDeLaEducacionProgramasMultidisciplinariosOGenerales
        agronomiaSilviculturaYPesca
        literatura
        otro
        filosofiaYetica
        industriaDeLaAlimentacion
        biologiaYBioquimica
        psicologia
        artesYHumanidades
        poderLegislativo
        formacionDocenteParaEducacionBasicaNivelPrimaria
        didacticaPedagogiaYCurriculo
        chofer
        enfermeriaYCuidados
        salud
        contabilidadYFiscalizacion
        formacionDocente
        diseno
        programasMultidisciplinariosOGenerales
        economia
        finanzasBancaYSeguros
        areaFisicoMatematicasYLasIngenierias
        serviciosPersonales
        formacionDocenteParaLaEnsenanzaDeAsignaturasEspecificas
        cuidadoDeNinos
        quimica
        sindicatosYOOrganizacionesPoliticas
        desemplead
        electricidadYGeneracionDeEnergia
        cienciasFisicasQuimicasYDeLaTierra
        criminologia
        tecnologiaYProteccionDelMedioAmbiente
    }
`
export default occupationCategoryEnum
