Resources:
  FormResponsesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.env.FORM_RESPONSES_TABLE}
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
